[admin:devlens_handler]
match = /devlens
members = devlens_investigate

[admin_external:devlens_investigate]
handlertype = python
handlerfile = devlens_handler.py
handleractions = edit
python.version = python3
